# @package _global_

content:
  - _target_:  nbprint.ContentMarkdown
    content: |
      # ${..name}
    css: ":scope { text-align: center; }"
  - _target_:  nbprint.ContentPageBreak
  - _target_:  nbprint.ContentTableOfContents
  - _target_:  nbprint.ContentPageBreak
