---
debug: false
outputs:
  _target_:  nbprint.NBConvertOutputs
  path_root: ./examples/output
  target: "html"

content:
  - _target_:  nbprint.ContentMarkdown
    content: |
      # A Generic Report
      ## A Subtitle
    css: ":scope { text-align: center; }"

  - _target_:  nbprint.ContentPageBreak

  - _target_:  nbprint.ContentTableOfContents

  - _target_:  nbprint.ContentPageBreak

  - _target_:  nbprint.ContentMarkdown
    content: |
      # Section One
      Lorem ipsum dolor sit amet.
      ## Subsection One
      Consectetur adipiscing elit, sed do eiusmod tempor incididunt.
      ## Subsection Two
      Ut labore et dolore magna aliqua.

  - _target_:  nbprint.ContentPageBreak

  - _target_:  nbprint.ContentFlexRowLayout
    sizes: [1, 1]
    content:
      - _target_:  nbprint.ContentFlexColumnLayout
        content:
          - _target_:  nbprint.ContentMarkdown
            content: |
              # Section Two
              Lorem ipsum dolor sit amet.
              ## Subsection One
              Consectetur adipiscing elit, sed do eiusmod tempor incididunt.

      - _target_:  nbprint.ContentFlexColumnLayout
        content:
          - _target_:  nbprint.ContentMarkdown
            content: |
              # Section Three
              Ut labore et dolore magna aliqua.
              ## Subsection One
              Ut enim ad minim veniam, quis nostrud.
