name: Build Status

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - docs/
      - LICENSE
      - README.md
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        python-version: [3.11]
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v5

    - uses: actions-ext/python/setup@main
      with:
        version: ${{ matrix.python-version }}

    - uses: actions-ext/node/setup@main
      with:
        version: 22.x

    - name: Install pandoc via brew
      run: brew install pandoc
      if: ${{ matrix.os == 'macos-latest' }}

    - name: Install pandoc via apt
      run: sudo apt install pandoc
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Install dependencies
      run: make develop

    - name: Install chromium
      run: playwright install chromium

    - name: Build
      run: make build

    - name: Lint
      run: make lint

    - name: Test
      run: make tests
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.node-version }}
        path: '**/junit.xml'
      if: ${{ always() }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: '**/junit.xml'
      if: matrix.os == 'ubuntu-latest'

    - name: Upload coverage
      uses: codecov/codecov-action@v5

    - name: Upload generated reports (html)
      uses: actions/upload-artifact@v4
      id: upload-reports-html
      with:
        name: reports
        path: 'examples/output/*.html'
        if-no-files-found: error
        overwrite: true
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.11 && github.event_name == 'pull_request'

    - name: Upload generated reports (pdf)
      uses: actions/upload-artifact@v4
      id: upload-reports-pdf
      with:
        name: reports
        path: 'examples/output/*.pdf'
        if-no-files-found: error
        overwrite: true
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.11 && github.event_name == 'pull_request'

    - name: Find comment for generated reports
      uses: peter-evans/find-comment@v3
      id: find-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.11 && github.event_name == 'pull_request'

    - name: Update comment for generated reports
      uses: peter-evans/create-or-update-comment@v5
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        edit-mode: replace
        body: |-
            | Name                | Link                                                              |
            | :------------------ | :---------------------------------------------------------------- |
            | Test Reports (HTML) | [download](${{ steps.upload-reports-html.outputs.artifact-url }}) |
            | Test Reports (PDF)  | [download](${{ steps.upload-reports-pdf.outputs.artifact-url }})  |
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.11 && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == 'nbprint/nbprint'

    - name: Twine check
      run: make dist
